const PLAYER_NAME_SET = 'PLAYER_NAME_SET';
const PLAYER_SET_WINNER_FLAG_TRUE = 'PLAYER_SET_WINNER_FLAG_TRUE';
const PLAYER_SET_WINNER_FLAG_FALSE = 'PLAYER_SET_WINNER_FLAG_FALSE';
const PLAYER_SET_TIME_START_PLAY = 'PLAYER_SET_TIME_START_PLAY';
const PLAYER_SET_TIME_END_PLAY = 'PLAYER_SET_TIME_END_PLAY';
const PLAYER_SET_TIME_SCORE = 'PLAYER_SET_TIME_SCORE';
const PLAYER_RESET = 'PLAYER_RESET';

export {
  PLAYER_NAME_SET,
  PLAYER_SET_WINNER_FLAG_TRUE,
  PLAYER_SET_WINNER_FLAG_FALSE,
  PLAYER_SET_TIME_START_PLAY,
  PLAYER_SET_TIME_END_PLAY,
  PLAYER_SET_TIME_SCORE,
  PLAYER_RESET
};
