const GAME_START_SET_START = 'GAME_START_SET_START';
const GAME_START_SET_STOP = 'GAME_START_SET_STOP';
const GAME_START_FLAG_RESET = 'GAME_START_FLAG_RESET';

export { GAME_START_SET_START, GAME_START_SET_STOP, GAME_START_FLAG_RESET };
